name: Auditd Syntax Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update package information
        run: sudo apt update

      - name: Install auditd
        run: sudo apt install -y auditd

      - name: Start auditd
        run: if ! (systemctl is-active auditd); then sudo systemctl start auditd; fi

      - name: Remove default rules
        run: |
          sudo ls -l /etc/audit/rules.d/
          sudo rm /etc/audit/audit.rules
          sudo rm -rf /etc/audit/rules.d
          sudo mkdir /etc/audit/rules.d

      - name: Copy rules file to rules directory
        run: sudo cp $GITHUB_WORKSPACE/auditd.rules /etc/audit/rules.d/

      - name: Check rules
        run: sudo augenrules --check 2>&1

      # This will load the compiled rules file, check how many lines are in it, and display each line if successful
      - name: Load rules
        run: |
          sudo augenrules --load 2>&1
          sudo wc -l /etc/audit/audit.rules
          sudo auditctl -l
